### ISSUE TITLE
Unable set username

### ISSUE THREAD

**Issue by ppalma** [dragon3/rhythmbox-twitter-plugin#12]
when I click the button "set your username" nothing happen.

btw, I'm using python-httplib2-0.4.0-4.fc12.noarch
## so the traceback as follow

 Traceback (most recent call last):
  File "/home/ppalma/.gnome2/rhythmbox/plugins/twitter-plugin/twitter-plugin.py", line 417, in connect
    self.plugin.connect_twitter_account()
  File "/home/ppalma/.gnome2/rhythmbox/plugins/twitter-plugin/twitter-plugin.py", line 337, in connect_twitter_account
    request_token = self.get_request_token(client)
  File "/home/ppalma/.gnome2/rhythmbox/plugins/twitter-plugin/twitter-plugin.py", line 368, in get_request_token
    resp, content = client.request(TWITTER_URLS['request_token'], "GET")
  File "/home/ppalma/.gnome2/rhythmbox/plugins/twitter-plugin/oauth2/**init**.py", line 628, in request
    connection_type=connection_type)
  File "/usr/lib/python2.6/site-packages/httplib2/**init**.py", line 1050, in request
    (response, content) = self._request(conn, authority, uri, request_uri, method, body, headers, redirections, cachekey)
  File "/usr/lib/python2.6/site-packages/httplib2/__init__.py", line 854, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/usr/lib/python2.6/site-packages/httplib2/__init__.py", line 823, in _conn_request
    conn.request(method, request_uri, body, headers)
  File "/usr/lib/python2.6/httplib.py", line 874, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.6/httplib.py", line 911, in _send_request
    self.endheaders()
  File "/usr/lib/python2.6/httplib.py", line 868, in endheaders
    self._send_output()
  File "/usr/lib/python2.6/httplib.py", line 740, in _send_output
    self.send(msg)
  File "/usr/lib/python2.6/httplib.py", line 699, in send
    self.connect()
  File "/usr/lib/python2.6/site-packages/httplib2/__init__.py", line 736, in connect
    sock.settimeout(self.timeout)
  File "<string>", line 1, in settimeout
TypeError: a float is required

**Comment by dragon3** [comment]
Thank you, ppalma.

This is httplib2's problem, see bellow.
http://code.google.com/p/httplib2/issues/detail?id=42&can=1&q=float

So, you should install newer httplib2.

**Comment by ppalma** [comment]
fixed 
ty

**Comment by dragon3** [comment]
Thank you, ppalma!
