### ISSUE TITLE
Can not start Twitter Plugin

### ISSUE THREAD

**Issue by leomeloxp** [dragon3/rhythmbox-twitter-plugin#13]
Hi, I was trying to start the plugin on Ubuntu 11.04 and when I try to check the box to activate it, it shows an error:
"Plugin Error: Unable to activate Twitter Plugin" - I took a look at the terminal and this is what it reports when I try to activate the plugin. Is there a known way to fix it?

```
  File "/home/leo/.gnome2/rhythmbox/plugins/twitter-plugin/twitter-plugin.py", line 39, in <module>
    from twitter import Api, User
ImportError: No module named twitter
(rhythmbox:11888): Rhythmbox-WARNING **: Could not load plugin twitter-plugin
(rhythmbox:11888): Rhythmbox-WARNING **: Error, impossible to activate plugin 'Twitter plugin'
Traceback (most recent call last):
  File "/home/leo/.gnome2/rhythmbox/plugins/twitter-plugin/twitter-plugin.py", line 39, in <module>
    from twitter import Api, User
ImportError: No module named twitter
(rhythmbox:11888): Rhythmbox-WARNING **: Could not load plugin twitter-plugin
(rhythmbox:11888): Rhythmbox-WARNING **: Error, impossible to activate plugin 'Twitter plugin'
```

Thanks in advance =]

**Comment by dragon3** [comment]
Hi! leo-san.
Please install python libralies.

$ sudo apt-get install python-httplib2 python-gconf python-gobject python-gtk2 python-gnome2 python-glade2 python-twitter

**Comment by petrizzo** [comment]
Hi! I have the same problem since 4-5 days. This is the output I have:

petrizzo@neruda:~/.gnome2/rhythmbox/plugins$ rhythmbox 
(rhythmbox:14645): GLib-GObject-CRITICAL *_: g_object_set_qdata: assertion `G_IS_OBJECT (object)' failed
(rhythmbox:14645): Rhythmbox-WARNING *_: Could not open device /dev/radio0
(rhythmbox:14645): Rhythmbox-WARNING *_: Unable to grab media player keys: Could not get owner of name 'org.gnome.SettingsDaemon': no such name
(rhythmbox:14645): GLib-CRITICAL *_: g_str_has_suffix: assertion `str != NULL' failed
Traceback (most recent call last):
  File "/home/petrizzo/.gnome2/rhythmbox/plugins/rhythmbox-twitter-plugin/twitter-plugin.py", line 39, in <module>
    from twitter import Api, User
ImportError: cannot import name Api
(rhythmbox:14645): Rhythmbox-WARNING *_: Could not load plugin twitter-plugin
(rhythmbox:14645): Rhythmbox-WARNING *_: Error, impossible to activate plugin 'Twitter plugin'

(at pastebin http://pastebin.com/fmLSgy5e)

I have all the libraries you suggest updated.

Thanks in advance!!

**Comment by dragon3** [comment]
Hi, petrizzo
Please check your python-twitter's version?

$ apt-cache show python-twitter

**Comment by petrizzo** [comment]
Hi!!

This is what I got

Package: python-twitter
Priority: optional
Section: universe/python
Installed-Size: 264
Maintainer: Ubuntu MOTU Developers ubuntu-motu@lists.ubuntu.com
Original-Maintainer: Mauro Lizaur mauro@cacavoladora.org
Architecture: all
Version: 0.6-1ubuntu1
Depends: python, python-support (>= 0.90.0), python-simplejson (>= 2.0.9)
Suggests: www-browser
Filename: pool/universe/p/python-twitter/python-twitter_0.6-1ubuntu1_all.deb
Size: 31258
MD5sum: b6f1fe91cfc260ac58ce853eb9efd316
SHA1: 526fe9d49609a2c417720a851b762f906ebe8d95
SHA256: e16c791e1de32adfcd4b570f5ee216382ebf59492f3437d004692cc5459d7591
Description: Twitter API wrapper for Python
 This library provides a pure Python interface for the Twitter API.
 .
 Twitter provides a service that allows people to connect via the web, IM, and
 SMS. Twitter exposes a web services API (http://twitter.com/help/api) and this
 library is intended to make it even easier for Python programmers to use.
Homepage: http://code.google.com/p/python-twitter/
Python-Version: 2.6
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Origin: Ubuntu

**Comment by nicolenin** [comment]
Hi 

Sorry im new in Ubuntu and try to do this but i cant i made all thigs seems that i cant unpack:

prometeo@prometeo-laptop:~$ sudo apt-get install python-httplib2 python-gconf python-gobject python-gtk2 python-gnome2 python-glade2 python-twitter
[sudo] password for prometeo: 
Leyendo listas de paquetes... Hecho
Creando árbol de dependencias  
Leyendo la información de estado... Hecho
python-gconf ya está en su versión más reciente.
python-glade2 ya está en su versión más reciente.
python-gnome2 ya está en su versión más reciente.
python-gtk2 ya está en su versión más reciente.
fijado python-gtk2 como instalado manualmente.
python-httplib2 ya está en su versión más reciente.
python-gobject ya está en su versión más reciente.
Los paquetes indicados a continuación se instalaron de forma automática y ya no son necesarios.
  libgladeui-1-11 wine1.2-gecko libqt3-mt
Utilice «apt-get autoremove» para eliminarlos.
Se instalarán los siguientes paquetes NUEVOS:
  python-twitter
0 actualizados, 1 se instalarán, 0 para eliminar y 19 no actualizados.
Necesito descargar 30,0 kB de archivos.
Se utilizarán 270 kB de espacio de disco adicional después de esta operación.
¿Desea continuar [S/n]? s
Des:1 http://cl.archive.ubuntu.com/ubuntu/ oneiric/universe python-twitter all 0.6-1ubuntu2 [30,0 kB]
Descargados 30,0 kB en 1seg. (20,8 kB/s)  
Seleccionando el paquete python-twitter previamente no seleccionado.
(Leyendo la base de datos ... 244538 ficheros o directorios instalados actualmente.)
Desempaquetando python-twitter (de .../python-twitter_0.6-1ubuntu2_all.deb) ...
Procesando disparadores para man-db ...
Configurando python-twitter (0.6-1ubuntu2) ...
Procesando disparadores para python-support ...
prometeo@prometeo-laptop:~$  cd /tmp
prometeo@prometeo-laptop:/tmp$ wget http://github.com/dragon3/rhythmbox-twitter-plugin/tarball/master
--2011-11-08 03:51:42--  http://github.com/dragon3/rhythmbox-twitter-plugin/tarball/master
Resolviendo github.com... 207.97.227.239
Conectando a github.com|207.97.227.239|:80... conectado.
Petición HTTP enviada, esperando respuesta... 301 Moved Permanently
Ubicación: https://github.com/dragon3/rhythmbox-twitter-plugin/tarball/master [siguiente]
--2011-11-08 03:51:42--  https://github.com/dragon3/rhythmbox-twitter-plugin/tarball/master
Conectando a github.com|207.97.227.239|:443... conectado.
Petición HTTP enviada, esperando respuesta... 302 Found
Ubicación: https://nodeload.github.com/dragon3/rhythmbox-twitter-plugin/tarball/master [siguiente]
--2011-11-08 03:51:43--  https://nodeload.github.com/dragon3/rhythmbox-twitter-plugin/tarball/master
Resolviendo nodeload.github.com... 207.97.227.252
Conectando a nodeload.github.com|207.97.227.252|:443... conectado.
Petición HTTP enviada, esperando respuesta... 200 OK
Longitud: 20228 (20K) [application/octet-stream]
Guardando en: «master»

100%[=====================================================================================================================================>] 20.228      74,0K/s   en 0,3s    

2011-11-08 03:51:45 (74,0 KB/s) - «master» guardado [20228/20228]

prometeo@prometeo-laptop:/tmp$  tar zxfv dragon3-rhythmbox-twitter-plugin-_.tar.gz
tar (child): dragon3-rhythmbox-twitter-plugin-_.tar.gz: No se puede open: No existe el archivo o el directorio
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

This should be easy for you, not for me, thanks
